spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usedcar?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    #prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  web:
#将图片服务器路径配置为静态路径(包含原有的静态路径)
    resources:
      static-locations: classpath:/static/**,classpath:/resources/**,file:${imgFile}


server:
  port: 8888
  servlet:
    context-path: /usedcar

#图片的访问路径配置(物理路径)
imgFile: E:\upload\

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wsc.entity



